"use client";
import { useState } from 'react';
export function ProductsManager({ categories }: { categories: any[] }) {
  const [newCategory, setNewCategory] = useState({ slug: '', name_he: '', sort_order: 0, image_url: '' });
  const [newProduct, setNewProduct] = useState({ category_id: '', name_he: '', description_he: '', image_url: '', sort_order: 0 });
  async function createCategory() { const response = await fetch('/api/admin/categories', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(newCategory) }); if (!response.ok) return alert('שגיאה ביצירת קטגוריה'); location.reload(); }
  async function createProduct() { const response = await fetch('/api/admin/products', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(newProduct) }); if (!response.ok) return alert('שגיאה ביצירת מוצר'); location.reload(); }
  return <div className="space-y-8"><div className="rustic-card rounded-[2rem] p-6"><h2 className="mb-4 text-2xl font-bold gold-text">יצירת קטגוריה</h2><div className="grid gap-4 md:grid-cols-4"><input value={newCategory.slug} onChange={(e) => setNewCategory({ ...newCategory, slug: e.target.value })} placeholder="slug" className="input-base" /><input value={newCategory.name_he} onChange={(e) => setNewCategory({ ...newCategory, name_he: e.target.value })} placeholder="שם בעברית" className="input-base" /><input value={newCategory.image_url} onChange={(e) => setNewCategory({ ...newCategory, image_url: e.target.value })} placeholder="קישור תמונה" className="input-base" /><button onClick={createCategory} className="gold-btn rounded-full px-6 py-3 font-black">שמירה</button></div></div><div className="rustic-card rounded-[2rem] p-6"><h2 className="mb-4 text-2xl font-bold gold-text">יצירת מוצר</h2><div className="grid gap-4 md:grid-cols-5"><select value={newProduct.category_id} onChange={(e) => setNewProduct({ ...newProduct, category_id: e.target.value })} className="input-base"><option value="">בחירת קטגוריה</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name_he}</option>)}</select><input value={newProduct.name_he} onChange={(e) => setNewProduct({ ...newProduct, name_he: e.target.value })} placeholder="שם מוצר" className="input-base" /><input value={newProduct.image_url} onChange={(e) => setNewProduct({ ...newProduct, image_url: e.target.value })} placeholder="קישור תמונה" className="input-base" /><input value={newProduct.description_he} onChange={(e) => setNewProduct({ ...newProduct, description_he: e.target.value })} placeholder="תיאור" className="input-base" /><button onClick={createProduct} className="gold-btn rounded-full px-6 py-3 font-black">שמירה</button></div></div><div className="space-y-4">{categories.map((category) => <div key={category.id} className="rustic-card rounded-[2rem] p-6"><h3 className="text-2xl font-bold gold-text">{category.name_he}</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{category.products?.map((product: any) => <div key={product.id} className="rounded-2xl border border-amber-100/15 bg-black/20 p-4"><div className="font-bold">{product.name_he}</div><div className="mt-1 text-sm text-stone-300">{product.description_he || 'ללא תיאור'}</div></div>)}</div></div>)}</div></div>;
}
