"use client";
import { useState } from 'react';
export function PromotionManager({ promotions }: { promotions: any[] }) {
  const [form, setForm] = useState({ title_he: '', description_he: '', image_url: '', is_active: true });
  async function createPromotion() { const response = await fetch('/api/promotions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!response.ok) return alert('שגיאה ביצירת מבצע'); location.reload(); }
  async function remove(id: string) { await fetch(`/api/admin/promotions/${id}`, { method: 'DELETE' }); location.reload(); }
  async function toggle(id: string, is_active: boolean) { await fetch(`/api/admin/promotions/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ is_active: !is_active }) }); location.reload(); }
  return <section className="mx-auto max-w-7xl px-4 py-12"><h1 className="mb-8 text-4xl font-black gold-text">ניהול מבצעים</h1><div className="mb-8 rustic-card rounded-[2rem] p-6"><h2 className="mb-4 text-2xl font-bold gold-text">יצירת מבצע חדש</h2><div className="grid gap-4 md:grid-cols-2"><input placeholder="כותרת" value={form.title_he} onChange={(e) => setForm({ ...form, title_he: e.target.value })} className="input-base" /><input placeholder="קישור לתמונה" value={form.image_url} onChange={(e) => setForm({ ...form, image_url: e.target.value })} className="input-base" /><textarea placeholder="תיאור המבצע" value={form.description_he} onChange={(e) => setForm({ ...form, description_he: e.target.value })} className="input-base md:col-span-2" rows={5} /></div><button onClick={createPromotion} className="gold-btn mt-4 rounded-full px-6 py-3 font-black">שמירת מבצע</button></div><div className="space-y-4">{promotions.map((promotion) => <article key={promotion.id} className="rustic-card rounded-[2rem] p-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h3 className="text-2xl font-bold gold-text">{promotion.title_he}</h3><p className="mt-2 max-w-3xl text-stone-200">{promotion.description_he}</p></div><div className="flex gap-3"><button onClick={() => toggle(promotion.id, promotion.is_active)} className="rounded-full border border-amber-100/20 px-4 py-2">{promotion.is_active ? 'כיבוי' : 'הפעלה'}</button><button onClick={() => remove(promotion.id)} className="rounded-full border border-red-300/30 px-4 py-2 text-red-200">מחיקה</button></div></div></article>)}</div></section>;
}
